export const DOM = {
    BTN_SETTINGS: document.getElementById('btn-settings'),
    MODAL_SETTINGS: document.getElementById('modal-settings'),
    BTN_SAVE: document.getElementById('btn-save-settings'),
    INPUT_NAME: document.getElementById('input-name'),
    BTN_DECREASE: document.getElementById('btn-decrease'),
    BTN_INCREASE: document.getElementById('btn-increase'),
    DISPLAY_PERCENT: document.getElementById('display-percent'),
    CHECK_BOLD: document.getElementById('check-bold'),
    RESULT_CONTAINER: document.getElementById('result-container'),
    LOADER: document.getElementById('loader'),
    OUTPUT_TEXT: document.getElementById('output-message'),
    OUTPUT_IMAGE: document.getElementById('output-image'),
    COMPLIMENTS: document.getElementById('btn-compliment'),
    INSULTES: document.getElementById('btn-insulte'),
    DECLARATIONS: document.getElementById('btn-declaration'),
};